### PR TITLE
docs: Update references to old branch name

### PR DESCRIPTION
**Pull request by nya-elimuai**
ref https://github.com/elimu-ai/wiki/issues/127

### CODE REVIEW

**Comment by nya-elimuai** [comment]
@JairoFra Could you review the file changes at https://github.com/elimu-ai/webapp/pull/1543/files?

**Comment by JairoFra** [comment]
LGTM

**Review by JairoFra — APPROVED** [review]
LGTM

**Review by jpatel3 — APPROVED** [review]
looks fine.

**Pull request merged**
