### PR TITLE
1636 upgrade to jetty 100x

### PR DESCRIPTION
**Pull request by vrudas**

### CODE REVIEW

**Comment by vrudas** [comment]
Not sure why CI fails only on Windows build, comparing to Linux or macOS are success

**Comment by jo-elimu** [comment]
> Not sure why CI fails only on Windows build, comparing to Linux or macOS are success

@vrudas I pressed "Re-run all jobs," and now all the unit tests succeeded:  https://github.com/elimu-ai/webapp/actions/runs/7297926036?pr=1640

So it must have been a temporary problem.

**Review by jo-elimu — DISMISSED** [review]
Thank you, @vrudas 🙂

The page at https://eclipse.dev/jetty/download.php says that version 10 of Jetty uses Servlet 4.0 and JSP 2.3. I think we are already at Servlet version 4.0, but only JSP version 2.2:
```xml
        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>jsp-api</artifactId>
            <version>2.2</version>
            <scope>provided</scope>
        </dependency>
```

Can we upgrade JSP from version 2.2 to 2.3 also?

I noticed that there is a version 2.3.x available, but under a different `artifactId` ("javax.servlet.jsp-api" instead of "jsp-api"): https://repo.maven.apache.org/maven2/javax/servlet/jsp/javax.servlet.jsp-api/

**Comment by vrudas** [comment]
@jo-elimu thanks for notice, will try to update JSP dependency also, and notify you after completion

**Pull request merged**
