### PR TITLE
#1341 Upgrade to jQuery 3.6.0

### PR DESCRIPTION
**Pull request by Shubham-Vishwakarma**
https://github.com/elimu-ai/webapp/issues/1341

### CODE REVIEW

**Comment by Shubham-Vishwakarma** [comment]
Source file: https://code.jquery.com/jquery-3.6.0.min.js

**Comment by nya-elimuai** [comment]
@Shubham-Vishwakarma Thanks. Did you test if any functionality on the website stopped working after the upgrade?

**Comment by Shubham-Vishwakarma** [comment]
@nya-elimuai It seems ok to me.

**Review by nya-elimuai — APPROVED** [review]
Ok, looks good! Ready to be merged 👍

**Pull request merged**
