### PR TITLE
Disabled the Javadoc plugin in pom.xml

### LINKED ISSUE #1802: Remove Javadoc plugin
Disable Javadoc plugin in `pom.xml`.

### PR DESCRIPTION
**Pull request by charanbhatia**
Modify the configuration of the maven-javadoc-plugin. This pull request disables the Javadoc plugin in our Maven build process. 
closed #1802
Changes:
Added <skip>true</skip> to the <configuration> section.
Changed the <phase> to none for the attach-javadocs execution.

### CODE REVIEW

**Review by jo-elimu — CHANGES_REQUESTED** [review]
@charanbhatia Instead of adjusting the existing configuration, please remove the whole plugin from the POM file, since we will not be needing Javadoc at all for the webapp. The Javadoc will mostly be relevant for the https://github.com/elimu-ai/model JAR library.

**Comment by charanbhatia** [comment]
> @charanbhatia Instead of adjusting the existing configuration, please remove the whole plugin from the POM file, since we will not be needing Javadoc at all for the webapp. The Javadoc will mostly be relevant for the https://github.com/elimu-ai/model JAR library.

Done. Please re-review the PR

**Review by jo-elimu — CHANGES_REQUESTED** [review]
Does not compile: https://github.com/elimu-ai/webapp/actions/runs/10233442927/job/28315804611

**Comment by charanbhatia** [comment]
@jo-elimu made a new commit with the appropriate changes. Please check it and give the feedback.

**Review by jo-elimu — CHANGES_REQUESTED** [review]
@charanbhatia Please compile your code changes and run the webapp locally before opening a pull request.

**Pull request closed without merging**
