### PR TITLE
#571 - minor code fixes:

### PR DESCRIPTION
**Pull request by aschworer**
Sorry for the relatively big merge request. It contains not that many changes, but in more places than expected.
I can try to split it to several MR each per one type of change.
It will take some time though. Let me know if I should.

Here:

- removed unused variables & redundant declarations
- upgraded few constructions to use java 5 (i.e. loops vs. for-each)
- upgraded few constructions to use java 7 (i.e. try-catch blocks)
- upgraded few constructions to use java 8 capabilities (i.e. lambdas, .removeIf)
- replaces few Collections.sort() with list.sort()
- replaced access to static variable from object to class levels (i.e. return soundType.VOWEL; replaced with return SoundType.VOWEL;)
- replaced Arrays.asList() with only 1 argument with Collections.singletonList() for better performance
- string concatenations in a loop (which are hard on space and performance) replaced with StringBuilder
- removed identical catch blocks (if exception handling is same)

### CODE REVIEW

**Comment by aschworer** [comment]
@jo-elimuai 
With the changes introduces in this MR, I think it would be nice to upgrade jetty-maven-plugin to version 9.3.0.M2 (currently it is version 8.1.14.v20131031).

Without upgrade, because of some Java8 constructions which were added, I start getting some warnings on Jetty start: `[WARNING] EXCEPTION java.lang.ArrayIndexOutOfBoundsException: 52264`

Google says it's nothing really serious, but upgrading Jetty plugin to version 9 fixes this problem, as it's compatible with Java8.

Let me know if there is any reason not to upgrade, and in this case it might make sense to revert Java8 constructions.

**Comment by jo-elimuai** [comment]
> With the changes introduces in this MR, I think it would be nice to upgrade jetty-maven-plugin to version 9.3.0.M2 (currently it is version 8.1.14.v20131031).

When upgrading the Maven plugin, we must simultaneously upgrade the standalone Jetty server on the test/prod server to the same version, right?

**Comment by jo-elimuai** [comment]
Can you split this pull request in to smaller pieces to make it easier to review?

**Comment by aschworer** [comment]
> When upgrading the Maven plugin, we must simultaneously upgrade the standalone Jetty server on the test/prod server to the same version, right?

Not nesessarily. I think it's easier to upgrade the plugin first, and test it for couple of days locally, and if everything seem fine, try upgrading the TEST server, and then only PROD.

The pull request for the plugin is already open: https://github.com/elimu-ai/webapp/pull/601

**Comment by aschworer** [comment]
> Can you split this pull request in to smaller pieces to make it easier to review?
Will do it after the upgrade

**Pull request closed without merging**
