### PR TITLE
refactor: #1423 Reduce the length of the contract ABI used by the get…

### PR DESCRIPTION
**Pull request by nya-elimuai**
…Balance function

### CODE REVIEW

**Review by cravend — APPROVED** [review]
Seems to work for me! Note: I don't have any Elimu token in my Metamask account, so I can't say if the balance is accurate.

**Comment by nya-elimuai** [comment]
> Seems to work for me! Note: I don't have any Elimu token in my Metamask account, so I can't say if the balance is accurate.

@cravend Now you do 😉 
https://rinkeby.etherscan.io/tx/0xdf9bf483861c1ab8037eca5dc9f580b172d4993ace7f4d32a0061c10d0f270dc

**Comment by cravend** [comment]
> > Seems to work for me! Note: I don't have any Elimu token in my Metamask account, so I can't say if the balance is accurate.
> 
> @cravend Now you do 😉
> https://rinkeby.etherscan.io/tx/0xdf9bf483861c1ab8037eca5dc9f580b172d4993ace7f4d32a0061c10d0f270dc

Somehow, I inputted the wrong address into Gitcoin :( I'm trying to figure out what happened because I just used the WalletConnect protocol, but my public address is actually `0xD6F72C33009E81fab7E583080f430B027529d1f1`. Thank you anyway for the coins, once I figure out what happened I'll definitely use them for testing ;)

**Comment by nya-elimuai** [comment]
> Somehow, I inputted the wrong address into Gitcoin :( I'm trying to figure out what happened because I just used the WalletConnect protocol, but my public address is actually `0xD6F72C33009E81fab7E583080f430B027529d1f1`. Thank you anyway for the coins, once I figure out what happened I'll definitely use them for testing ;)

@cravend Okay, sent to. the other address as well: https://rinkeby.etherscan.io/tx/0xd1f72480b41d185c7b4c660db1cc5ccbf8847face924e8af1e341f54845fd7d6

**Pull request merged**
